# Generated by Django 3.1 on 2021-07-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
